#ifndef CALCTYPES_H_INCLUDED__
#define CALCTYPES_H_INCLUDED__
#pragma once

typedef enum flag_t
{
	SUCCESS, //0
	FILE_OPPENING_ERROR, //1
	NUMBER_OF_ARGUMENTS_ERROR, //2
	MEMORY_ERROR, //3
	READING_ERROR, //4
	WRITING_ERROR,//5
	COMMENT_STR, //6
	EMPTY_STR, //7
	EXPRESSION_STR, //8
	END_STR, //9
	EMPTY_STACK, //10
	LEX_ERROR, //11
	BRACKETS_ERROR, //12
	PARSING_ERROR, //13
	CALCULATING_ERROR //14
} flag_t; 


#endif //CALCTYPES_H_INCLUDED__
